version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:11
        environment:
          CI: true
    working_directory: ~/mst-gql

jobs:
  build:
    executor: my-executor
    steps:
      - checkout

      - restore_cache:
          name: restore .cache/yarn
          keys:
            - yarn-cache-{{ arch }}
      - restore_cache:
          name: restore node_modules
          keys:
            - node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-modules-{{ arch }}-{{ .Branch }}
            - node-modules-{{ arch }}

      - run: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          name: cache .cache/yarn
          key: yarn-cache-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: cache node_modules
          key: node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  # mobx-state-tree tests
  test-dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .

      - run: yarn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

      - test-dev:
          requires:
            - build
